- name: Generate an ignition file
  become: false
  collections:
    - containers.podman
  podman_container:
    name: ignition
    image: quay.io/coreos/butane:release
    command: ["--pretty","/tmp/butane.bu","-o","/tmp/ignition.ign"]
    state: started
    recreate: true
    auto_remove: true
    volumes:
      - "{{ playbook_dir }}:/tmp:z"
  tags:
    - ignition


- name: Get URL for stable images
  uri:
    url: https://builds.coreos.fedoraproject.org/streams/stable.json
    method: GET
  register: stable_list
  tags: url

- name: Test if decompressed image exists and is of right cksum
  stat:
    path: "{{ playbook_dir }}/fcos.qcow2"
    get_checksum: true
    checksum_algorithm: sha256
  register: decompressed_img

- name: Test if compressed image exists and is of right cksum
  stat:
    path: "fcos.qcow2.xz"
    get_checksum: true
    checksum_algorithm: sha256
  register: compressed_img

- name: test
  debug:
    msg: "{{ stable_list.json | json_query('architectures.aarch64.artifacts.qemu.formats.\"qcow2.xz\".disk.sha256') }}"
  register: cksum_compress

- name: Get compressed image
  get_url:
    url: "{{ stable_list.json | json_query('architectures.aarch64.artifacts.qemu.formats.\"qcow2.xz\".disk.location') }}"
    dest: "fcos.qcow2.xz"
    #checksum: sha256:{{ cksum_compress }}
    mode: '0600'
    validate_certs: yes
  register: download_result
  when:
    - (not decompressed_img.stat.exists and not compressed_img.stat.exists) or (compressed_img.stat.sha256 != stable_list.json | json_query('architectures.aarch64.artifacts.qemu.formats."qcow2.xz".disk.sha256'))
